<a href="https://colab.research.google.com/github/hoangchaulanbao/HocmayNC/blob/main/HMNC_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import các thư viện sau:

numpy (as np)

pandas

RandomForestClassifier from sklearn.ensemble

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

Bước 1 Load dataset

Đọc dữ liệu

Đọc data từ github

In [ ]:
#url = "https://raw.githubusercontent.com/user/repo/main/home.csv"
url ="https://raw.githubusercontent.com/hoangchaulanbao/HocmayNC/refs/heads/main/23_HOMES.csv"
df = pd.read_csv(url)
df.head()

,Selling_Price,List_Price,Area,Acres,Age,Taxes,Rooms,Bedrooms,Baths_full
0,400000,414000,2704,2.27,27,4920,9,3,3
1,370000,379000,2096,0.75,21,4113,8,4,2
2,382500,389900,2737,1.00,36,6072,9,4,2
3,300000,299900,1800,0.43,34,4024,8,4,2
4,305000,319900,1066,3.60,69,3562,6,3,2

In [ ]:
my_data = pd.read_csv("Data/23_HOMES.csv", delimiter=",")
my_data[0:5]

,Selling_Price,List_Price,Area,Acres,Age,Taxes,Rooms,Bedrooms,Baths_full
0,400000,414000,2704,2.27,27,4920,9,3,3
1,370000,379000,2096,0.75,21,4113,8,4,2
2,382500,389900,2737,1.00,36,6072,9,4,2
3,300000,299900,1800,0.43,34,4024,8,4,2
4,305000,319900,1066,3.60,69,3562,6,3,2

Kích thước dữ liệu

In [ ]:
my_data.shape

(40, 9)

**Bước 2.Tiền xử lý dữ liệu**


my_data là 23_HOMES.csv sau khi đọc vào pandas dataframe, chúng ta định nghĩa các tham số sau:

**X** as the Ma trận thuộc tính (data of my_data)

**Y **as the Vector
- Selling_price **(target)**
- Feature (List_Price, Area, Acres, Age, Taxes, Rooms, Bedrooms, Baths_full)

In [ ]:
# Lệnh drop sẽ bỏ cột 'Selling_Price' đi, lấy tất cả các cột còn lại làm X
X = my_data.drop(columns=['Selling_Price'])
Y = my_data['Selling_Price']

**Bước 3 - Chia dữ liệu**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)